spring:
  application:
    name: dynamic-route
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true
    username: root
    #Mac的密码：
    password: root123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #Mac的redis
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
    password:

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath*:mapper/*Dao.xml
  type-aliases-package: com.yidiandian.entity

#分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


server:
  port: 9098

logging:
  file: log/dynamic-route.log
  level:
    com.yidiandian.dao: debug

eureka:
  instance:
    hostname: localhost
  client:
    #自己不是一个客户端
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
